import React from 'react';
import { Edit3 } from 'lucide-react';
import { AccountStatusDropdown, AccountStatus } from './AccountStatusDropdown.tsx';
import { VerifyToggle } from './VerifyToggle.tsx';
import { AdminCurrency } from './EditBalanceModal.tsx';

export interface AdminProfile { id: string; email: string; verified: boolean; account_status: AccountStatus; balances: Record<string, number>; country: string | null; created_at: string; last_sign_in?: string | null; }
interface UserTableProps { users: AdminProfile[]; onBalance: (user: AdminProfile) => void; onVerified: (user: AdminProfile, value: boolean) => void; onStatus: (user: AdminProfile, value: AccountStatus) => void; busyId?: string | null; }
const currencies: AdminCurrency[] = ['USD', 'EUR', 'GBP', 'NGN', 'BTC', 'ETH'];
export const UserTable: React.FC<UserTableProps> = ({ users, onBalance, onVerified, onStatus, busyId }) => <div className="overflow-x-auto border border-cyan-300/15 bg-[#071021] shadow-[0_20px_80px_rgba(0,0,0,.25)]"><table className="w-full min-w-[1100px] text-left text-xs"><thead className="border-b border-white/10 bg-white/[0.03] text-[10px] uppercase tracking-widest text-zinc-500"><tr><th className="px-4 py-4">Client</th><th className="px-4 py-4">Created / last sign-in</th><th className="px-4 py-4">Country</th><th className="px-4 py-4">Balances</th><th className="px-4 py-4">Verified</th><th className="px-4 py-4">Account status</th><th className="px-4 py-4">Action</th></tr></thead><tbody className="divide-y divide-white/5">{users.map((user) => <tr key={user.id} className="hover:bg-cyan-300/[0.03]"><td className="px-4 py-4"><div className="font-medium text-white">{user.email}</div><div className="mt-1 font-mono text-[10px] text-zinc-600">{user.id}</div></td><td className="px-4 py-4 font-mono text-zinc-400">{new Date(user.created_at).toLocaleDateString()}<br /><span className="text-zinc-600">{user.last_sign_in ? new Date(user.last_sign_in).toLocaleString() : 'Never signed in'}</span></td><td className="px-4 py-4 text-zinc-300">{user.country || 'Not provided'}</td><td className="px-4 py-4"><div className="grid grid-cols-3 gap-x-4 gap-y-1 font-mono text-[10px]">{currencies.map((currency) => <span key={currency} className="text-zinc-400">{currency} <b className="text-zinc-200">{Number(user.balances?.[currency] || 0).toLocaleString()}</b></span>)}</div></td><td className="px-4 py-4"><VerifyToggle verified={user.verified} disabled={busyId === user.id} onChange={(value) => onVerified(user, value)} /></td><td className="px-4 py-4"><AccountStatusDropdown value={user.account_status} disabled={busyId === user.id} onChange={(value) => onStatus(user, value)} /></td><td className="px-4 py-4"><button onClick={() => onBalance(user)} className="flex items-center gap-2 border border-cyan-300/25 px-3 py-2 text-cyan-200 hover:bg-cyan-300/10"><Edit3 className="h-3.5 w-3.5" />Edit</button></td></tr>)}</tbody></table>{users.length === 0 && <div className="p-12 text-center text-sm text-zinc-500">No profiles match these filters.</div>}</div>;
